[workspace]
members = [
    "lib/migration"
]

[package]
name = "photon"
version = "0.1.0"
authors = ["Helius Labs"]
homepage = "https://helius.dev"
license = "AGPL-3.0"
keywords = ["solana", "photon"]

[workspace.dependencies]
sea-orm = { version = "0.12", features = ["sqlx-postgres", "tokio", "macros" ] }